# Generated by Django 4.0.5 on 2022-07-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='pfps/user-default.png', null=True, upload_to='pfps/'),
        ),
    ]
