# Generated by Django 4.0.5 on 2022-07-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_profile_social_youtube'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created']},
        ),
    ]
